/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.39
 * Generated at: 2015-02-24 13:17:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("\t<head>\n");
      out.write("\t\t<meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("\t\t<meta charset=\"utf-8\">\n");
      out.write("\t\t<title>Cab Application</title>\n");
      out.write("\t\t<meta name=\"generator\" content=\"Bootply\" />\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1\">\n");
      out.write("\t\t<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("\t\t<link href=\"css/styles.css\" rel=\"stylesheet\">\n");
      out.write("\t</head>\n");
      out.write("\t<body onload=\"refreshDash();\">\n");
      out.write("<nav class=\"navbar navbar-inverse navbar-fixed-top\" role=\"navigation\">\n");
      out.write("      <div class=\"container-fluid\">\n");
      out.write("        <div class=\"navbar-header\">\n");
      out.write("            <p class=\"navbar-text\">Enterprise Project Cab</p>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"navbar-collapse collapse\">\n");
      out.write("          <ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("           <li><a href=\"Home.jsp\">Dashboard</a></li>\n");
      out.write("\t\t\t<li><a href=\"booking.htm\">Booking</a></li>\n");
      out.write("            <li><a href=\"setting.htm\">Settings</a></li>\n");
      out.write("            <li><a href=\"#\">Help</a></li>\n");
      out.write("            <li><a href=\"logout\">Logout</a></li>\n");
      out.write("          </ul>\n");
      out.write("         </div>\n");
      out.write("      </div>\n");
      out.write("</nav>\n");

boolean flag=false;
if(session.getAttribute("userid")!=null){
	flag=true; 
}
/* String UserId=session.getAttribute("userid").toString();
boolean isAdmin=false;
int count=0;
for(int i=0;i<UserId.length();i++)
{
	if(Character.isDigit(UserId.charAt(i))||Character.isLetter(UserId.charAt(i)))
	{
		count++;
	}
}
if(count<UserId.length())
{
	isAdmin=true;
} */
if(!flag)
{

      out.write("\n");
      out.write("<form action=\"login\">\n");
      out.write("\t<!-- Modal -->\n");
      out.write("<div class=\"modal fade\" id=\"myModal\" tabindex=\"-1\" role=\"dialog\" \n");
      out.write("   aria-labelledby=\"myModalLabel\" aria-hidden=\"true\" data-backdrop=\"static\">\n");
      out.write("   <div class=\"modal-dialog\" id=\"modd\">\n");
      out.write("      <div class=\"modal-content\">\n");
      out.write("         <div class=\"modal-header\">\n");
      out.write("\t\t    \n");
      out.write("            <h4 class=\"modal-title\" id=\"myModalLabel\">\n");
      out.write("               <font size=\"3\">Enterprise Project Cab</font>\n");
      out.write("            </h4>\n");
      out.write("         </div>\n");
      out.write("         <div class=\"modal-body\">\n");
      out.write("            <table>\n");
      out.write("\t\t\t<tr>\n");
      out.write("\t\t\t\t<td><label><b>Enter your Associate Id<font color=\"red\">*</font>&nbsp;&nbsp;&nbsp; : &nbsp;&nbsp;&nbsp;</b></label></td>\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"userId\" placeholder=\"Your Associate Id\" class=\"form-control\" style=\"width:250px;\" /></td>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t\t</table>\n");
      out.write("\t\t\t\n");
      out.write("         </div>\n");
      out.write("         <div class=\"modal-footer\">\n");
      out.write("           <!--  <button type=\"button\" class=\"btn btn-primary\" data-dismiss=\"modal\">\n");
      out.write("               Submit\n");
      out.write("            </button> -->\n");
      out.write("            <input type=\"submit\" value=\"Submit\" class=\"btn btn-primary\" />\n");
      out.write("            \n");
      out.write("         </div>\n");
      out.write("      </div>\n");
      out.write("   </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\t\n");
      out.write("</form>\n");
}
      out.write("\n");
      out.write("<form class=\"form-dashboard\">\n");
      out.write("\n");

String name="";
if(session.getAttribute("username")!=null){
	name=(String)session.getAttribute("username"); 


      out.write("\n");
      out.write("<font style=\"text-align: center;\">");
      out.print("Welcome "+name);
      out.write("</font>\n");
} 
      out.write("\n");
      out.write("<br/>\n");
      out.write("\t\n");
      out.write("\n");
      out.write("    <div class=\"col-sm-8 col-md-12 main\">\n");
      out.write("    \n");
      out.write("           <div class=\"row\">\n");
      out.write("    \n");
      out.write("\t\t <div class=\"col-md-4 col-sm-4\">\n");
      out.write("                    <div class=\"panel panel-info\">\n");
      out.write("                        <div class=\"panel-heading\">\n");
      out.write("                            DASHBOARD\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                  <div class=\"panel-body scrollpanel\" style=\"height:460px\" id=\"dashboard\">\n");
      out.write("              \t\t\n");
      out.write("\n");
      out.write("                  </div><!-- /panel-body -->\n");
      out.write("              </div><!-- /panel -->\n");
      out.write("\t\n");
      out.write("          \n");
      out.write("          </div>\n");
      out.write("\t\t   \n");
      out.write("\t\t   <div class=\"col-lg-8 col-right\">\n");
      out.write("\t\t   <div id=\"page-wrapper\" >\n");
      out.write("            <div id=\"page-inner\">\n");
      out.write("                                        \n");
      out.write("            <div class=\"row\">\n");
      out.write("                    <div class=\"panel panel-primary\" style=\"height:500px;width:812px\">\n");
      out.write("                        <div class=\"panel-heading\">\n");
      out.write("                            CAB INFORMATION\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"panel-body scrollpanel\" style=\"height:455px\" >\n");
      out.write("\t\t\t\t\t\t<table id=\"tbody\">\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <tr>\n");
      out.write("\t\t\t\t\t\t\t\t  <td><b>Cab Number : </b></td>\n");
      out.write("\t\t\t\t\t\t\t\t  <td>9239</td>\n");
      out.write("\t\t\t\t\t\t\t\t  <td>&nbsp;&nbsp;&nbsp;</td>\n");
      out.write("\t\t\t\t\t\t\t\t  <td>&nbsp;&nbsp;&nbsp;</td>\n");
      out.write("\t\t\t\t\t\t\t\t  <td><b>Cab Timing : </b></td>\n");
      out.write("\t\t\t\t\t\t\t\t  <td>07:30 PM</td> \n");
      out.write("\t\t\t\t\t\t\t\t</tr> \n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t  <td><b>Cab Driver Name : </b></td>\n");
      out.write("\t\t\t\t\t\t\t\t  <td>Pappu</td>\n");
      out.write("\t\t\t\t\t\t\t\t  <td>&nbsp;&nbsp;&nbsp;</td>\n");
      out.write("\t\t\t\t\t\t\t\t  <td>&nbsp;&nbsp;&nbsp;</td>\n");
      out.write("\t\t\t\t\t\t\t\t  <td><b>Cab Driver Number : </b></td>\n");
      out.write("\t\t\t\t\t\t\t\t  <td>9876541230</td>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t  <td><b>Cab Direction : </b></td>\n");
      out.write("\t\t\t\t\t\t\t\t  <td>South</td>\n");
      out.write("\t\t\t\t\t\t\t\t  <td>&nbsp;&nbsp;&nbsp;</td>\n");
      out.write("\t\t\t\t\t\t\t\t  <td>&nbsp;&nbsp;&nbsp;</td>\n");
      out.write("\t\t\t\t\t\t\t\t  <td><b>Cab Route : </b></td>\n");
      out.write("\t\t\t\t\t\t\t\t  <td>Ruby</td>\n");
      out.write("\t\t\t\t\t\t\t\t</tr> -->\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t</table>\n");
      out.write("\t\t\t\t\t\t\t<br/>\n");
      out.write("\t\t\t\t\t\t<table class=\"table\" id=\"usertable\">\n");
      out.write("\t\t\t\t\t\t<!-- \t<tbody>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t  \n");
      out.write("\t\t\t\t\t\t\t\t  <th>Associate Id</th>\n");
      out.write("\t\t\t\t\t\t\t\t  <th>Associate Name</th>\n");
      out.write("\t\t\t\t\t\t\t\t  <th>Associate Phone Number</th>\n");
      out.write("\t\t\t\t\t\t\t\t  <th>Associate Email</th>\n");
      out.write("\t\t\t\t\t\t\t\t  <th></th>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t  \n");
      out.write("\t\t\t\t\t\t\t\t  <td>389777</td>\n");
      out.write("\t\t\t\t\t\t\t\t  <td>Suresh Shivale</td>\n");
      out.write("\t\t\t\t\t\t\t\t  <td>9869564272</td>\n");
      out.write("\t\t\t\t\t\t\t\t  <td>example@cognizant.com</td>\n");
      out.write("\t\t\t\t\t\t\t\t  <td></td>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>  \n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t  \n");
      out.write("\t\t\t\t\t\t\t\t  <td>426169</td>\n");
      out.write("\t\t\t\t\t\t\t\t  <td>Saikat Bhattacharya</td>\n");
      out.write("\t\t\t\t\t\t\t\t  <td>9831791558</td>\t\t\t\t\t\t\t\t  \n");
      out.write("\t\t\t\t\t\t\t\t  <td>example1@cognizant.com</td>\n");
      out.write("\t\t\t\t\t\t\t\t  <td></td>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t  \n");
      out.write("\t\t\t\t\t\t\t\t  <td>426146</td>\n");
      out.write("\t\t\t\t\t\t\t\t  <td>Subhodip Dutta</td>\t \n");
      out.write("\t\t\t\t\t\t\t\t  <td>8272563698</td>\n");
      out.write("\t\t\t\t\t\t\t\t  <td>example2@cognizant.com</td>\t\n");
      out.write("\t\t\t\t\t\t\t\t  <td>\n");
      out.write("\t\t\t\t\t\t\t\t  <a href=\"booking.htm\"><img class=\"addIcon\" width=\"20\" height=\"20\" style=\"display:inline;\" title=\"\" alt=\"Add Icon\" \n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"images/add.png\" data-original-title=\"Click to add Associate\"></a>\n");
      out.write("\t\t\t\t\t\t\t\t  </td>\t\t\t\t\t\t\t\t  \n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t</tbody> -->\t\n");
      out.write("\t\t\t\t\t\t</table>\n");
      out.write("\t\t\t\t\t       \n");
      out.write("\t\t\t\t\t </div>       \n");
      out.write("\t\t\t\t </div> \n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t  \n");
      out.write("\t\t  \n");
      out.write("\t\t  </div><!-- // page wraper -->\n");
      out.write("\t\t</div>\n");
      out.write("\t  </div>\n");
      out.write("\n");
      out.write("     \n");
      out.write("\t</div>\n");
      out.write("\t\n");
      out.write("</form>\n");
      out.write("<hr>\n");
      out.write("<footer>\n");
      out.write("\n");
      out.write("  <p class=\"text-center\">©2014 Cognizant Technology Solutions</p>\n");
      out.write("</footer>\n");
      out.write("        \n");
      out.write("\t<!-- script references -->\n");
      out.write("\t<script src=\"js/jquery-1.10.2.js\"></script>\n");
      out.write("\t<script src=\"js/bootstrap.min.js\"></script>\n");
      out.write("\t<script src=\"js/scripts.js\"></script>\n");
      out.write("\t\t\n");
      out.write("<script>\n");
      out.write("   $(function () { \n");
      out.write("    $('#myModal').modal({});\n");
      out.write("     var winH = $(window).height();\n");
      out.write("\t var winW = $(window).width();\n");
      out.write("\n");
      out.write("\t// Set the popup window to center\n");
      out.write("\t$('#modd').css('top', winH / 3.5 - $('#modd').height()/2);\n");
      out.write("\t$('#modd').css('left', (winW / 2 - $('#modd').width())-($('#modd').width()/7));\n");
      out.write("\t \n");
      out.write("   \n");
      out.write("   });\n");
      out.write("   function refreshDash() {\n");
      out.write("\t  \n");
      out.write("\t     $.ajax({\n");
      out.write("\t       url : 'refreshdash',\n");
      out.write("\t       method : 'get',\n");
      out.write("\t       ContentType : 'json',\n");
      out.write("\t       data : {\n");
      out.write("\t    \t \n");
      out.write("\t       },\n");
      out.write("\t       success : function(response) {\n");
      out.write("\t    \t   \n");
      out.write("\t    \t   var div = '';\n");
      out.write("\t    \t   var width=0;\n");
      out.write("\t\t         if (response != null) {\n");
      out.write("\t\t           $(response).each(function(index, value) {\n");
      out.write("\t\t        \t   var info=value.cabNum+\"|\"+value.cabTime+\"|\"+value.cabRoute;\n");
      out.write("\t\t \t\t\twidth=(value.seatCount/value.cabCapacity)*100;\n");
      out.write("\t\t             div = div +'<button type=\"button\" class=\"btn btn-link btn-sm\" onclick=\"getCabClickInfoUser(\\'' + info + '\\');\"><font size=\"2\">'+value.cabNum+' - <font color=\"green\">'+value.cabTime+' PM</font> - <font color=\"#ed9c28\">'+value.cabRoute+'</font></font></button>'+ \n");
      out.write("         \t\t\t'<div class=\"progress\">'+\n");
      out.write("    \t\t\t\t '<div class=\"progress-bar progress-bar-success\" role=\"progressbar\" aria-valuenow=\"50\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width:'+width+'%\">'+\n");
      out.write("         \t\t\t '</div>'+'</div>'\n");
      out.write("\t\t             \n");
      out.write("\t\t             \n");
      out.write("\t\t           });\n");
      out.write("\t\t           div=div+'<button type=\"button\" class=\"btn btn-warning btn-sm\" onclick=\"refresh()\">Refresh Dashboard</button>';\n");
      out.write("\t\t           $('#dashboard').html(div);\n");
      out.write("\t\t          \n");
      out.write("\t\t         }\n");
      out.write("\t\t         refreshCabTableData();\n");
      out.write("\t\t         refreshUserTableData();\n");
      out.write("\t       }\n");
      out.write("\t     });\n");
      out.write("\t   }\n");
      out.write("   function refreshCabTableData()\n");
      out.write("   {\n");
      out.write("\t   \n");
      out.write("\t   $.ajax({\n");
      out.write("\t       url : 'refreshCabTableData',\n");
      out.write("\t       method : 'get',\n");
      out.write("\t       ContentType : 'json',\n");
      out.write("\t       data : {\n");
      out.write("\t    \t \n");
      out.write("\t       },\n");
      out.write("\t  success : function(response) {\n");
      out.write("\t\t    \t   \n");
      out.write("\t\t    \t   var div = '';\n");
      out.write("\t\t\t         if (response != null) {\n");
      out.write("\t\t\t          \n");
      out.write("\t\t\t          var obj=JSON.parse(JSON.stringify(response));\n");
      out.write("\t\t\t          div='<tr>'+\n");
      out.write("\t\t\t\t\t  '<td><b>Cab Number : </b></td>'+\n");
      out.write("\t\t\t\t\t  '<td>'+obj.cabNumber+'</td><td>&nbsp;&nbsp;&nbsp;</td><td>&nbsp;&nbsp;&nbsp;</td><td><b>Cab Timing : </b></td>'+\n");
      out.write("\t\t\t\t\t  '<td>'+obj.cabTime+' PM</td>' +'</tr>'+\n");
      out.write("\t\t\t\t\t  '<tr>'+\n");
      out.write("\t\t\t\t\t  '<td><b>Cab Driver Name : </b></td>'+\n");
      out.write("\t\t\t\t\t  '<td>'+obj.cabDriverName+'</td><td>&nbsp;&nbsp;&nbsp;</td><td>&nbsp;&nbsp;&nbsp;</td><td><b>Cab Driver Number : </b></td>'+\n");
      out.write("\t\t\t\t\t  '<td>'+obj.cabDriverPhone+'</td>' +'</tr>'+\n");
      out.write("\t\t\t\t\t  '<tr>'+\n");
      out.write("\t\t\t\t\t  '<td><b>Cab Direction : </b></td>'+\n");
      out.write("\t\t\t\t\t  '<td>'+obj.cabDirection+'</td><td>&nbsp;&nbsp;&nbsp;</td><td>&nbsp;&nbsp;&nbsp;</td><td><b>Cab Route :: </b></td>'+\n");
      out.write("\t\t\t\t\t  '<td>'+obj.cabRoute+'</td>' +'</tr>'; \n");
      out.write("\t\t\t          $('#tbody').html(div);\n");
      out.write("\t\t\t          \n");
      out.write("\t\t\t         }\n");
      out.write("\t\t       }\n");
      out.write("\t\t    });\n");
      out.write("   }\n");
      out.write("\tfunction refreshUserTableData()\n");
      out.write("\t{\n");
      out.write("\t\t $.ajax({\n");
      out.write("\t\t       url : 'refreshUserTableData',\n");
      out.write("\t\t       method : 'get',\n");
      out.write("\t\t       ContentType : 'json',\n");
      out.write("\t\t       data : {\n");
      out.write("\t\t    \t \n");
      out.write("\t\t       },\n");
      out.write("\t\t  success : function(response) {\n");
      out.write("\t\t\t    \t   \n");
      out.write("\t\t\t    \t   var div = '';\n");
      out.write("\t\t\t    \t   var data='';\n");
      out.write("\t\t\t    \t   var tab='<tr><th>Associate Id</th><th>Associate Name</th><th>Associate Phone Number</th><th>Associate Email</th><th></th></tr>';\n");
      out.write("\t\t\t\t         if (response != null) \n");
      out.write("\t\t\t\t         {\n");
      out.write("\t\t\t\t        \t \n");
      out.write("\t\t\t\t        \t $(response).each(function(index, value) {\n");
      out.write("\t\t\t\t        \t\t div=div+'<tr><td>'+value.userId+'</td><td>'+value.userName+'</td><td>'+value.userPhone+'</td><td>'+value.userEmail+'</td><td></td></tr>' \n");
      out.write("\t\t\t\t        \t });\n");
      out.write("\t\t\t\t        \t data=tab+div;\n");
      out.write("\t\t\t\t        \t $('#usertable').html(data);\n");
      out.write("\t\t\t\t         }\n");
      out.write("\t\t\t\t         else\n");
      out.write("\t\t\t\t        \t{\n");
      out.write("\t\t\t\t        \t\tdata=tab;\n");
      out.write("\t\t\t\t        \t\t$('#usertable').html(data);\n");
      out.write("\t\t\t\t        \t}\n");
      out.write("\t\t\t       }\n");
      out.write("\t\t\t    });\n");
      out.write("\t}\n");
      out.write("\tfunction getCabClickInfoUser(s)\n");
      out.write("\t{\n");
      out.write("\t\t var cabnum=s.substr(0,s.indexOf(\"|\"));\n");
      out.write("\t\t var rest=s.substr(s.indexOf(\"|\")+1);\n");
      out.write("\t\t var cabTime=rest.substr(0,rest.indexOf(\"|\"));\n");
      out.write("\t\t var cabRoute=rest.substr(rest.indexOf(\"|\")+1);\n");
      out.write("\t\t $.ajax({\n");
      out.write("\t\t       url : 'getCabClickInfoUser',\n");
      out.write("\t\t       method : 'get',\n");
      out.write("\t\t       ContentType : 'json',\n");
      out.write("\t\t       data :\"cabNum=\"+cabnum+\"&cabRoute=\"+cabRoute+\"&cabTime=\"+cabTime,\n");
      out.write("\t\t  \t   success : function(response) { \n");
      out.write("\t\t  \t\t var div = '';\n");
      out.write("\t\t    \t var data='';\n");
      out.write("\t\t    \t var tab='<tr><th>Associate Id</th><th>Associate Name</th><th>Associate Phone Number</th><th>Associate Email</th><th></th></tr>';\n");
      out.write("\t\t\t\t        if (response != null) \n");
      out.write("\t\t\t\t         {\n");
      out.write("\t\t\t\t        \t$('#usertable').html('');\n");
      out.write("\t\t\t\t        \t $(response).each(function(index, value) {\n");
      out.write("\t\t\t\t        \t\t div=div+'<tr><td>'+value.userId+'</td><td>'+value.userName+'</td><td>'+value.userPhone+'</td><td>'+value.userEmail+'</td><td></td></tr>' \n");
      out.write("\t\t\t\t        \t });\n");
      out.write("\t\t\t\t        \t data=tab+div;\n");
      out.write("\t\t\t\t        \t $('#usertable').html(data);\n");
      out.write("\t\t\t\t         }\n");
      out.write("\t\t\t\t        else\n");
      out.write("\t\t\t\t        \t{\n");
      out.write("\t\t\t\t        \t\tdata=tab;\n");
      out.write("\t\t\t\t        \t\t$('#usertable').html(data);\n");
      out.write("\t\t\t\t        \t}\n");
      out.write("\t\t\t       }\n");
      out.write("\t\t \t\t\n");
      out.write("\t\t\t    });\n");
      out.write("\t\t getCabClickInfoCab(s);\n");
      out.write("\t}\n");
      out.write("\tfunction getCabClickInfoCab(s)\n");
      out.write("\t{\n");
      out.write("\t\t var cabnum=s.substr(0,s.indexOf(\"|\"));\n");
      out.write("\t\t var rest=s.substr(s.indexOf(\"|\")+1);\n");
      out.write("\t\t var cabTime=rest.substr(0,rest.indexOf(\"|\"));\n");
      out.write("\t\t var cabRoute=rest.substr(rest.indexOf(\"|\")+1);\n");
      out.write("\t\t $.ajax({\n");
      out.write("\t\t       url : 'getCabClickInfoCab',\n");
      out.write("\t\t       method : 'get',\n");
      out.write("\t\t       ContentType : 'json',\n");
      out.write("\t\t       data :\"cabNum=\"+cabnum+\"&cabRoute=\"+cabRoute+\"&cabTime=\"+cabTime,\n");
      out.write("\t\t  \t   success : function(response) { \n");
      out.write("\t\t  \t\t \t\tvar div = '';\n");
      out.write("\t\t\t\t        if (response != null) \n");
      out.write("\t\t\t\t         {\n");
      out.write("\t\t\t\t        \t$('#tbody').html('');\n");
      out.write("\t\t\t\t        \tvar obj=JSON.parse(JSON.stringify(response));\n");
      out.write("\t\t\t\t\t          div='<tr>'+\n");
      out.write("\t\t\t\t\t\t\t  '<td><b>Cab Number : </b></td>'+\n");
      out.write("\t\t\t\t\t\t\t  '<td>'+obj.cabNumber+'</td><td>&nbsp;&nbsp;&nbsp;</td><td>&nbsp;&nbsp;&nbsp;</td><td><b>Cab Timing : </b></td>'+\n");
      out.write("\t\t\t\t\t\t\t  '<td>'+obj.cabTime+' PM</td>' +'</tr>'+\n");
      out.write("\t\t\t\t\t\t\t  '<tr>'+\n");
      out.write("\t\t\t\t\t\t\t  '<td><b>Cab Driver Name : </b></td>'+\n");
      out.write("\t\t\t\t\t\t\t  '<td>'+obj.cabDriverName+'</td><td>&nbsp;&nbsp;&nbsp;</td><td>&nbsp;&nbsp;&nbsp;</td><td><b>Cab Driver Number : </b></td>'+\n");
      out.write("\t\t\t\t\t\t\t  '<td>'+obj.cabDriverPhone+'</td>' +'</tr>'+\n");
      out.write("\t\t\t\t\t\t\t  '<tr>'+\n");
      out.write("\t\t\t\t\t\t\t  '<td><b>Cab Direction : </b></td>'+\n");
      out.write("\t\t\t\t\t\t\t  '<td>'+obj.cabDirection+'</td><td>&nbsp;&nbsp;&nbsp;</td><td>&nbsp;&nbsp;&nbsp;</td><td><b>Cab Route :: </b></td>'+\n");
      out.write("\t\t\t\t\t\t\t  '<td>'+obj.cabRoute+'</td>' +'</tr>'; \n");
      out.write("\t\t\t\t\t          $('#tbody').html(div);\n");
      out.write("\t\t\t\t         }\n");
      out.write("\t\t\t       }\n");
      out.write("\t\t\t    });\n");
      out.write("\t\t\n");
      out.write("\t}\n");
      out.write("</script>\n");
      out.write("\t</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
