/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.39
 * Generated at: 2015-02-27 12:47:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Settings_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005fform_0026_005fid_005fcommandName_005fclass;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fclass_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005fselect_0026_005fpath_005fonchange_005fid_005fclass;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005foption_0026_005fvalue_005flabel_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005foptions_0026_005fitems_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fid_005fclass_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fform_005fform_0026_005fid_005fcommandName_005fclass = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fclass_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fform_005fselect_0026_005fpath_005fonchange_005fid_005fclass = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fform_005foption_0026_005fvalue_005flabel_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fform_005foptions_0026_005fitems_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fid_005fclass_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fform_005fform_0026_005fid_005fcommandName_005fclass.release();
    _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fclass_005fnobody.release();
    _005fjspx_005ftagPool_005fform_005fselect_0026_005fpath_005fonchange_005fid_005fclass.release();
    _005fjspx_005ftagPool_005fform_005foption_0026_005fvalue_005flabel_005fnobody.release();
    _005fjspx_005ftagPool_005fform_005foptions_0026_005fitems_005fnobody.release();
    _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fid_005fclass_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t\t<meta charset=\"utf-8\">\r\n");
      out.write("\t\t<title>Cab Application</title>\r\n");
      out.write("\t\t<meta name=\"generator\" content=\"Bootply\" />\r\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1\">\r\n");
      out.write("\t\t<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\t<link href=\"css/styles.css\" rel=\"stylesheet\">\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("<nav class=\"navbar navbar-inverse navbar-fixed-top\" role=\"navigation\">\r\n");
      out.write("      <div class=\"container-fluid\">\r\n");
      out.write("        <div class=\"navbar-header\">\r\n");
      out.write("            <p class=\"navbar-text\">Enterprise Project Cab</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"navbar-collapse collapse\">\r\n");
      out.write("          <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("            <li><a href=\"Home.jsp\">Dashboard</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"booking.htm\">Booking</a></li>\r\n");
      out.write("            <li><a href=\"setting.htm\">Settings</a></li>\r\n");
      out.write("            <li><a href=\"#\">Help</a></li>\r\n");
      out.write("            <li><a href=\"logout\">Logout</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("</nav>\r\n");
      //  form:form
      org.springframework.web.servlet.tags.form.FormTag _jspx_th_form_005fform_005f0 = (org.springframework.web.servlet.tags.form.FormTag) _005fjspx_005ftagPool_005fform_005fform_0026_005fid_005fcommandName_005fclass.get(org.springframework.web.servlet.tags.form.FormTag.class);
      _jspx_th_form_005fform_005f0.setPageContext(_jspx_page_context);
      _jspx_th_form_005fform_005f0.setParent(null);
      // /Settings.jsp(30,0) null
      _jspx_th_form_005fform_005f0.setDynamicAttribute(null, "class", "form-dashboard");
      // /Settings.jsp(30,0) name = commandName type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fform_005f0.setCommandName("cabdto");
      // /Settings.jsp(30,0) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fform_005f0.setId("settingform");
      int[] _jspx_push_body_count_form_005fform_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_form_005fform_005f0 = _jspx_th_form_005fform_005f0.doStartTag();
        if (_jspx_eval_form_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write('\r');
            out.write('\n');

String name="";
String AdminCheck="";

if(session.getAttribute("username")!=null){
	name=(String)session.getAttribute("username"); 


            out.write("\r\n");
            out.write("<font style=\"text-align: center;\">");
            out.print("Welcome "+name);
            out.write("</font>\r\n");
}
name=(String)session.getAttribute("username"); 
AdminCheck=name.toUpperCase(); 
            out.write('\r');
            out.write('\n');

String userid="";
if(session.getAttribute("userid")!=null)
	{
	userid=(String)session.getAttribute("userid"); 
	}

            out.write("\r\n");
            out.write("<br/>\r\n");
            out.write("    <div class=\"col-sm-8 col-md-12 main\">\t   \r\n");
            out.write("\t   <div id=\"page-wrapper\">\r\n");
            out.write("\t\t<div id=\"page-inner\">\r\n");
            out.write("                                        \r\n");
            out.write("            <div class=\"row\">\r\n");
            out.write("               <div class=\"col-md-13 col-sm-13\">\r\n");
            out.write("                    <div class=\"panel panel-primary\"  style=\"height:480px;width:900px;margin-left:210px\">\r\n");
            out.write("                        <div class=\"panel-heading\">\r\n");
            out.write("                            CAB SETTINGS\r\n");
            out.write("                        </div>\r\n");
            out.write("                        \r\n");
            out.write("\t\t\t\t\t\t\t<div class=\"panel-body\">\r\n");
            out.write("                            <ul class=\"nav nav-tabs\">\r\n");
            out.write("                            \t<li class=\"active\"><a href=\"#settings\" data-toggle=\"tab\">Update Profile</a>\r\n");
            out.write("                                </li>                              \t\r\n");
            out.write("                                ");
                      
                                	 if(AdminCheck.equals("ADMIN"))
                                	 {
                                 
            out.write("                               \r\n");
            out.write("                                <li class=\"\"><a href=\"#home\" data-toggle=\"tab\">Add Cab</a>\r\n");
            out.write("                                </li>                                                           \r\n");
            out.write("                                <li class=\"\"><a href=\"#profile\" data-toggle=\"tab\">Manage Cab</a>\r\n");
            out.write("                                </li>                               \r\n");
            out.write("                                <li class=\"\"><a href=\"#adminsettings\" data-toggle=\"tab\">Manage Administrator</a>\r\n");
            out.write("                                </li>\r\n");
            out.write("                                ");
} 
            out.write("                               \r\n");
            out.write("                            </ul>\r\n");
            out.write("\r\n");
            out.write("                            <div class=\"tab-content\">\r\n");
            out.write("\t\t\t\t\t\t\t");
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t<div class=\"tab-pane fade active in\" id=\"settings\">\t\t \t\t \t\r\n");
            out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" value=\"updatecontact\" name=\"hidden\">\r\n");
            out.write("\t\t\t\t\t\t<br/>\r\n");
            out.write("\t\t\t\t\t\t  <table>\r\n");
            out.write("\t\t\t\t\t\t\t<tbody>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td><b>Associate ID <font color=\"red\">*</font></b></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td><b>:</b></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td>&nbsp;&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"userid\" disabled=\"disabled\" placeholder=\"Your Associate ID\" class=\"form-control input\" value=");
            out.print(userid);
            out.write("></td>\t\t\t\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td><b>Associate Email Id</b></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td><b>:</b></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td>&nbsp;&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"emailid\" placeholder=\"Your Email Id\" class=\"form-control input\"></td>\t\t\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td><span style=\"color:red\"  id=\"emailloc\"></span></td>\t\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td><b>Associate Contact Number</b></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td><b>:</b></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td>&nbsp;&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"contactno\"  placeholder=\"Your Contact Number\" class=\"form-control input\"></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td><span style=\"color:red\"  id=\"contactloc\"></span></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t</tr>                                                                                      \r\n");
            out.write("\t\t\t\t\t\t\t   </tbody>\t\r\n");
            out.write("\t\t\t\t   </table>\r\n");
            out.write("\t\t\t<br/><br/><br/><br/><br/><br/>\r\n");
            out.write("\t\t\t<input type=\"submit\" value=\"Change\" class=\"btn btn-primary\" onclick=\"submitSettingsForm('updatecontact')\" onsubmit=\"return validatecontact()\">\r\n");
            out.write("\t\t\t<input type=\"reset\" value=\"Cancel\" class=\"btn btn-primary\" onclick=\"window.location.href='Home.jsp'\">\r\n");
            out.write("\t\t\t<br>\r\n");
            out.write("\t\t\t ");
 
								String str1="";
								if(session.getAttribute("message")!=null){
									str1=(String)session.getAttribute("message"); 
								
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t<font color=\"red\"><span>");
            out.print(str1);
            out.write("</span></font>\r\n");
            out.write("\t\t\t\t\t\t\t\t");
} 
								session.removeAttribute("message");
								
            out.write("\r\n");
            out.write("\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\t\t ");
                      
                                	 if(AdminCheck.equals("ADMIN")){
                                 
            out.write(" \r\n");
            out.write("                               <div class=\"tab-pane fade\" id=\"home\">\r\n");
            out.write("                               <input type=\"hidden\" value=\"addcab\" name=\"hidden\">\r\n");
            out.write("\t\t\t\t\t\t\t\t<br/>\r\n");
            out.write("\t\t\t\t\t\t\t\t   <table>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<center>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<tbody>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td><b>Cab Number <font color=\"red\">*</font></b></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td><b>:</b></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td>&nbsp;&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td>");
            if (_jspx_meth_form_005finput_005f0(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
              return;
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td><span style=\"color:red\"  id=\"cabnoloc\"></span></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td><b>Driver Name <font color=\"red\">*</font></b></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td><b>:</b></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td>&nbsp;&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td>");
            if (_jspx_meth_form_005finput_005f1(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
              return;
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td><span style=\"color:red\"  id=\"dnameloc\"></span></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td><b>Driver Contact Number <font color=\"red\">*</font></b></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td><b>:</b></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td>&nbsp;&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td>");
            if (_jspx_meth_form_005finput_005f2(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
              return;
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td><span style=\"color:red\"  id=\"dphnloc\"></span></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t <tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td><b>Cab Capacity <font color=\"red\">*</font></b></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td><b>:</b></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td>&nbsp;&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td>");
            if (_jspx_meth_form_005finput_005f3(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
              return;
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td><span style=\"color:red\"  id=\"cabcapacityloc\"></span></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</tr>   \r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t</tr> \r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t <tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td><b>Cab POC <font color=\"red\">*</font></b></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td><b>:</b></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td>&nbsp;&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td>");
            if (_jspx_meth_form_005finput_005f4(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
              return;
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td><span style=\"color:red\"  id=\"cabpocloc\"></span></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</tr>                                                                                       \r\n");
            out.write("\t\t\t\t\t\t\t\t\t</tbody>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t\t\t\t\t</center>\r\n");
            out.write("\t\t\t\t\t\t</table>\r\n");
            out.write("\t\t\t\t\t\t<br/><br/>\r\n");
            out.write("\t\t\t\t\t\t\t<input type=\"button\" value=\"Add\" class=\"btn btn-primary\" onclick=\"submitSettingsForm('addCab')\">\r\n");
            out.write("\t\t\t\t\t\t\t<input type=\"reset\" value=\"Cancel\" class=\"btn btn-primary\" onclick=\"window.location.href='Home.jsp'\">\r\n");
            out.write("\t\t\t\t\t\t\t<br/>\r\n");
            out.write("\t\t\t\t\t\t\t ");
            out.write("\r\n");
            out.write("\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t");
            out.write("\r\n");
            out.write("\t\t\t\t\t\t<div class=\"tab-pane fade\" id=\"profile\">\r\n");
            out.write("\t\t\t\t\t\t<input type=\"hidden\" value=\"managecab\" name=\"hidden\">\r\n");
            out.write("\t\t\t\t\t\t<br/>\r\n");
            out.write("\t\t\t\t\t\t\t   <table>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<center>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<tbody>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td><b>Cab Number <font color=\"red\">*</font></b></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td><b>:</b></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td>&nbsp;&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<!-- <select class=\"form-control input\">\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"select\" selected>--Select--</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"north\">9231</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"east\">8626</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"west\">1123</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"south\">2581</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t</select> -->\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t");
            //  form:select
            org.springframework.web.servlet.tags.form.SelectTag _jspx_th_form_005fselect_005f0 = (org.springframework.web.servlet.tags.form.SelectTag) _005fjspx_005ftagPool_005fform_005fselect_0026_005fpath_005fonchange_005fid_005fclass.get(org.springframework.web.servlet.tags.form.SelectTag.class);
            _jspx_th_form_005fselect_005f0.setPageContext(_jspx_page_context);
            _jspx_th_form_005fselect_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
            // /Settings.jsp(236,11) null
            _jspx_th_form_005fselect_005f0.setDynamicAttribute(null, "class", "form-control input");
            // /Settings.jsp(236,11) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
            _jspx_th_form_005fselect_005f0.setId("cabnum");
            // /Settings.jsp(236,11) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
            _jspx_th_form_005fselect_005f0.setPath("cabNumber");
            // /Settings.jsp(236,11) name = onchange type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
            _jspx_th_form_005fselect_005f0.setOnchange("fillCabInfo()");
            int[] _jspx_push_body_count_form_005fselect_005f0 = new int[] { 0 };
            try {
              int _jspx_eval_form_005fselect_005f0 = _jspx_th_form_005fselect_005f0.doStartTag();
              if (_jspx_eval_form_005fselect_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                do {
                  out.write("\r\n");
                  out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
                  //  form:option
                  org.springframework.web.servlet.tags.form.OptionTag _jspx_th_form_005foption_005f0 = (org.springframework.web.servlet.tags.form.OptionTag) _005fjspx_005ftagPool_005fform_005foption_0026_005fvalue_005flabel_005fnobody.get(org.springframework.web.servlet.tags.form.OptionTag.class);
                  _jspx_th_form_005foption_005f0.setPageContext(_jspx_page_context);
                  _jspx_th_form_005foption_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fselect_005f0);
                  // /Settings.jsp(237,12) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                  _jspx_th_form_005foption_005f0.setValue("");
                  // /Settings.jsp(237,12) name = label type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                  _jspx_th_form_005foption_005f0.setLabel("--select--");
                  int[] _jspx_push_body_count_form_005foption_005f0 = new int[] { 0 };
                  try {
                    int _jspx_eval_form_005foption_005f0 = _jspx_th_form_005foption_005f0.doStartTag();
                    if (_jspx_th_form_005foption_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                      return;
                    }
                  } catch (java.lang.Throwable _jspx_exception) {
                    while (_jspx_push_body_count_form_005foption_005f0[0]-- > 0)
                      out = _jspx_page_context.popBody();
                    _jspx_th_form_005foption_005f0.doCatch(_jspx_exception);
                  } finally {
                    _jspx_th_form_005foption_005f0.doFinally();
                    _005fjspx_005ftagPool_005fform_005foption_0026_005fvalue_005flabel_005fnobody.reuse(_jspx_th_form_005foption_005f0);
                  }
                  out.write("\r\n");
                  out.write("\t\t\t                      \t\t\t\t");
                  if (_jspx_meth_form_005foptions_005f0(_jspx_th_form_005fselect_005f0, _jspx_page_context, _jspx_push_body_count_form_005fselect_005f0))
                    return;
                  out.write("\r\n");
                  out.write("\t\t\t\t\t\t\t\t\t\t\t");
                  int evalDoAfterBody = _jspx_th_form_005fselect_005f0.doAfterBody();
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
              }
              if (_jspx_th_form_005fselect_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
            } catch (java.lang.Throwable _jspx_exception) {
              while (_jspx_push_body_count_form_005fselect_005f0[0]-- > 0)
                out = _jspx_page_context.popBody();
              _jspx_th_form_005fselect_005f0.doCatch(_jspx_exception);
            } finally {
              _jspx_th_form_005fselect_005f0.doFinally();
              _005fjspx_005ftagPool_005fform_005fselect_0026_005fpath_005fonchange_005fid_005fclass.reuse(_jspx_th_form_005fselect_005f0);
            }
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td><b>Driver Name <font color=\"red\">*</font></b></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td><b>:</b></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td>&nbsp;&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td>");
            if (_jspx_meth_form_005finput_005f5(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
              return;
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td><span style=\"color:red\"  id=\"cabdriverloc\"></span></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td><b>Driver Contact Number <font color=\"red\">*</font></b></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td><b>:</b></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td>&nbsp;&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td>");
            if (_jspx_meth_form_005finput_005f6(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
              return;
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td><span style=\"color:red\"  id=\"drivercontactloc\"></span></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t <tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td><b>Cab Capacity <font color=\"red\">*</font></b></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td><b>:</b></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td>&nbsp;&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td>");
            if (_jspx_meth_form_005finput_005f7(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
              return;
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td><span style=\"color:red\"  id=\"cabcapacityloc\"></span></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t</tr> \r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t <tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td><b>Cab POC <font color=\"red\">*</font></b></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td><b>:</b></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td>&nbsp;&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td>");
            if (_jspx_meth_form_005finput_005f8(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
              return;
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td><span style=\"color:red\"  id=\"dcabpocloc\"></span></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</tr>                                                                                            \r\n");
            out.write("\t\t\t\t\t\t\t\t\t</tbody>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t\t\t\t\t</center>\r\n");
            out.write("\t\t\t\t\t\t</table>\r\n");
            out.write("\t\t\t\t\t\t<br/><br/>\r\n");
            out.write("\t\t\t\t\t\t\t<input type=\"submit\" value=\"Change\" class=\"btn btn-primary\" onclick=\"submitSettingsForm('managecab')\">\r\n");
            out.write("\t\t\t\t\t\t\t<input type=\"reset\" value=\"Cancel\" class=\"btn btn-primary\" onclick=\"window.location.href='Home.jsp'\">\r\n");
            out.write("\t\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t\r\n");
            out.write("\t\t\t<div class=\"tab-pane fade\" id=\"adminsettings\">\r\n");
            out.write("\t\t\t<input type=\"hidden\" value=\"manageadmin\" name=\"hidden\">\r\n");
            out.write("\t\t\t\t\t\t<br/>\r\n");
            out.write("\t\t\t\t\t\t  <table>\r\n");
            out.write("\t\t\t\t\t\t\t<tbody>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td><b>Administrator Id <font color=\"red\">*</font></b></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td><b>:</b></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td>&nbsp;&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"userid\" disabled=\"disabled\" placeholder=\"Your Administrator ID\" class=\"form-control input\" value=");
            out.print(userid);
            out.write("></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td><b>New Administrator Id <font color=\"red\">*</font></b></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td><b>:</b></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td>&nbsp;&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td><input type=\"text\" name=\"adminid\"  placeholder=\"Enter New Admin Id\" class=\"form-control input\"></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t</tr>                                                                                      \r\n");
            out.write("\t\t\t\t\t\t\t   </tbody>\t\r\n");
            out.write("\t\t\t\t   </table>\r\n");
            out.write("\t\t\t<br/><br/><br/><br/><br/><br/>\r\n");
            out.write("\t\t\t<input type=\"submit\" value=\"Change\" class=\"btn btn-primary\" onclick=\"submitSettingsForm('manageadmin')\">\r\n");
            out.write("\t\t\t<input type=\"reset\" value=\"Cancel\" class=\"btn btn-primary\" onclick=\"window.location.href='Home.jsp'\">\r\n");
            out.write("\t\t\t<br/><br/>\r\n");
            out.write("\t\t\t<b><font color=\"red\">Note:Session will be automatically logged out once the admin id gets updated</font></b>\r\n");
            out.write("\t\t\t</div>\r\n");
            out.write("\t\t\t\r\n");
            out.write("\t\t\t ");
 } 
            out.write("\r\n");
            out.write("\t\t\t \t\r\n");
            out.write("\t\t\t\r\n");
            out.write("\t\t </div>\r\n");
            out.write("\t\t</div>\r\n");
            out.write("                \r\n");
            out.write("                \r\n");
            out.write("       </div><!-- col-->\r\n");
            out.write("                   \r\n");
            out.write("          \r\n");
            out.write("    </div><!-- row-->\r\n");
            out.write("\t\t  \r\n");
            out.write("\t\t  \r\n");
            out.write("\t\t  </div> <!-- page inner-->\r\n");
            out.write("\t\t  \r\n");
            out.write("          </div><!-- page wraper-->\r\n");
            out.write("\t\r\n");
            out.write("     \r\n");
            out.write("\t</div><!-- main-->\r\n");
            out.write("\r\n");
            int evalDoAfterBody = _jspx_th_form_005fform_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_form_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_form_005fform_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_form_005fform_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_form_005fform_005f0.doFinally();
        _005fjspx_005ftagPool_005fform_005fform_0026_005fid_005fcommandName_005fclass.reuse(_jspx_th_form_005fform_005f0);
      }
      out.write("\r\n");
      out.write("<hr>\r\n");
      out.write("                       \r\n");
      out.write("<footer>\r\n");
      out.write("  <p class=\"text-center\">©2014 Cognizant Technology Solutions</p>\r\n");
      out.write("</footer>\r\n");
      out.write("<!-- script references -->\r\n");
      out.write("\t\t<script src=\"js/jquery-1.10.2.js\"></script>\r\n");
      out.write("\t\t<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"js/scripts.js\"></script>\r\n");
      out.write("         <script type=\"text/javascript\">\r\n");
      out.write("\t         function submitSettingsForm(a)\r\n");
      out.write("\t         {\r\n");
      out.write("\t         /* \tvar abc=document.getElementByName(\"hidden\").val();\r\n");
      out.write("\t         \tvar count=0;\r\n");
      out.write("\t         \tif(abc.equals(\"updatecontact\"))\r\n");
      out.write("\t         \t{\r\n");
      out.write("\t         \t\tvar phone=document.getElementById(\"contactloc\").value;\r\n");
      out.write("\t         \t\tvar valid=true;\r\n");
      out.write("\t         \t\tif(uphone.length!=10||!allnumeric(uphone)){\r\n");
      out.write("\t\t \t\t\t alert(\"enter a valid phone number\");  \r\n");
      out.write("\t\t \t\t\t count++;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}  */\r\n");
      out.write("\t\t\t\t    /* if(count==0){ */document.forms[0].action=a;\r\n");
      out.write("\t    \t    \t document.forms[0].submit();/* } */\r\n");
      out.write("\t\t        \t \r\n");
      out.write("\t\t      \r\n");
      out.write("\t        \t \r\n");
      out.write("\t         }\r\n");
      out.write("\t         function fillCabInfo() {\r\n");
      out.write("\t\t\t     var val = $('#cabnum').val();\r\n");
      out.write("\t\t\t     \r\n");
      out.write("\t\t\t     $.ajax({\r\n");
      out.write("\t\t\t       url : 'cabdetails',\r\n");
      out.write("\t\t\t       method : 'get',\r\n");
      out.write("\t\t\t       ContentType : 'json',\r\n");
      out.write("\t\t\t       data : {\r\n");
      out.write("\t\t\t    \t   cabnum : val\r\n");
      out.write("\t\t\t       },\r\n");
      out.write("\t\t\t       success : function(response) {\r\n");
      out.write("\t\t\t    \t   \r\n");
      out.write("\t\t\t         \r\n");
      out.write("\t\t\t         if (response != null) {\r\n");
      out.write("\t\t\t        \t var obj=JSON.parse(JSON.stringify(response));\r\n");
      out.write("\t\t\t        \t\r\n");
      out.write("\t\t\t        \tdocument.getElementById(\"dname\").value=obj.cabDriverName;\r\n");
      out.write("\t\t\t        \tdocument.getElementById(\"dph\").value=obj.cabDriverPhone;\r\n");
      out.write("\t\t\t        \tdocument.getElementById(\"cap\").value=\"\"+obj.cabCapacity;\r\n");
      out.write("\t\t\t        \tdocument.getElementById(\"poc\").value=obj.cabPoc;\r\n");
      out.write("\t\t\t         }\r\n");
      out.write("\t\t\t       }\r\n");
      out.write("\t\t\t     });\r\n");
      out.write("\t\t\t   }\r\n");
      out.write("        </script>\r\n");
      out.write("\t<!-- script references -->\r\n");
      out.write("\t\t<script src=\"js/jquery-1.10.2.js\"></script>\r\n");
      out.write("\t\t<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"js/scripts.js\"></script>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_form_005finput_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_form_005finput_005f0 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    _jspx_th_form_005finput_005f0.setPageContext(_jspx_page_context);
    _jspx_th_form_005finput_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
    // /Settings.jsp(147,14) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f0.setPath("cabNumber");
    // /Settings.jsp(147,14) null
    _jspx_th_form_005finput_005f0.setDynamicAttribute(null, "placeholder", "Cab Number");
    // /Settings.jsp(147,14) null
    _jspx_th_form_005finput_005f0.setDynamicAttribute(null, "class", "form-control input");
    int[] _jspx_push_body_count_form_005finput_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_form_005finput_005f0 = _jspx_th_form_005finput_005f0.doStartTag();
      if (_jspx_th_form_005finput_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005finput_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005finput_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005finput_005f0.doFinally();
      _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fclass_005fnobody.reuse(_jspx_th_form_005finput_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_form_005finput_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_form_005finput_005f1 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    _jspx_th_form_005finput_005f1.setPageContext(_jspx_page_context);
    _jspx_th_form_005finput_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
    // /Settings.jsp(159,14) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f1.setPath("cabDriverName");
    // /Settings.jsp(159,14) null
    _jspx_th_form_005finput_005f1.setDynamicAttribute(null, "placeholder", "Driver Name");
    // /Settings.jsp(159,14) null
    _jspx_th_form_005finput_005f1.setDynamicAttribute(null, "class", "form-control input");
    int[] _jspx_push_body_count_form_005finput_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_form_005finput_005f1 = _jspx_th_form_005finput_005f1.doStartTag();
      if (_jspx_th_form_005finput_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005finput_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005finput_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005finput_005f1.doFinally();
      _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fclass_005fnobody.reuse(_jspx_th_form_005finput_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_form_005finput_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_form_005finput_005f2 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    _jspx_th_form_005finput_005f2.setPageContext(_jspx_page_context);
    _jspx_th_form_005finput_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
    // /Settings.jsp(171,14) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f2.setPath("cabDriverPhone");
    // /Settings.jsp(171,14) null
    _jspx_th_form_005finput_005f2.setDynamicAttribute(null, "placeholder", "Driver Contact Number");
    // /Settings.jsp(171,14) null
    _jspx_th_form_005finput_005f2.setDynamicAttribute(null, "class", "form-control input");
    int[] _jspx_push_body_count_form_005finput_005f2 = new int[] { 0 };
    try {
      int _jspx_eval_form_005finput_005f2 = _jspx_th_form_005finput_005f2.doStartTag();
      if (_jspx_th_form_005finput_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005finput_005f2[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005finput_005f2.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005finput_005f2.doFinally();
      _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fclass_005fnobody.reuse(_jspx_th_form_005finput_005f2);
    }
    return false;
  }

  private boolean _jspx_meth_form_005finput_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_form_005finput_005f3 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    _jspx_th_form_005finput_005f3.setPageContext(_jspx_page_context);
    _jspx_th_form_005finput_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
    // /Settings.jsp(183,14) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f3.setPath("cabCapacity");
    // /Settings.jsp(183,14) null
    _jspx_th_form_005finput_005f3.setDynamicAttribute(null, "placeholder", "Cab Capacity");
    // /Settings.jsp(183,14) null
    _jspx_th_form_005finput_005f3.setDynamicAttribute(null, "class", "form-control input");
    int[] _jspx_push_body_count_form_005finput_005f3 = new int[] { 0 };
    try {
      int _jspx_eval_form_005finput_005f3 = _jspx_th_form_005finput_005f3.doStartTag();
      if (_jspx_th_form_005finput_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005finput_005f3[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005finput_005f3.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005finput_005f3.doFinally();
      _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fclass_005fnobody.reuse(_jspx_th_form_005finput_005f3);
    }
    return false;
  }

  private boolean _jspx_meth_form_005finput_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_form_005finput_005f4 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    _jspx_th_form_005finput_005f4.setPageContext(_jspx_page_context);
    _jspx_th_form_005finput_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
    // /Settings.jsp(195,14) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f4.setPath("cabPoc");
    // /Settings.jsp(195,14) null
    _jspx_th_form_005finput_005f4.setDynamicAttribute(null, "placeholder", "Cab Poc");
    // /Settings.jsp(195,14) null
    _jspx_th_form_005finput_005f4.setDynamicAttribute(null, "class", "form-control input");
    int[] _jspx_push_body_count_form_005finput_005f4 = new int[] { 0 };
    try {
      int _jspx_eval_form_005finput_005f4 = _jspx_th_form_005finput_005f4.doStartTag();
      if (_jspx_th_form_005finput_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005finput_005f4[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005finput_005f4.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005finput_005f4.doFinally();
      _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fclass_005fnobody.reuse(_jspx_th_form_005finput_005f4);
    }
    return false;
  }

  private boolean _jspx_meth_form_005foptions_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fselect_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fselect_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:options
    org.springframework.web.servlet.tags.form.OptionsTag _jspx_th_form_005foptions_005f0 = (org.springframework.web.servlet.tags.form.OptionsTag) _005fjspx_005ftagPool_005fform_005foptions_0026_005fitems_005fnobody.get(org.springframework.web.servlet.tags.form.OptionsTag.class);
    _jspx_th_form_005foptions_005f0.setPageContext(_jspx_page_context);
    _jspx_th_form_005foptions_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fselect_005f0);
    // /Settings.jsp(238,29) name = items type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005foptions_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cabnumlist}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int[] _jspx_push_body_count_form_005foptions_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_form_005foptions_005f0 = _jspx_th_form_005foptions_005f0.doStartTag();
      if (_jspx_th_form_005foptions_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005foptions_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005foptions_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005foptions_005f0.doFinally();
      _005fjspx_005ftagPool_005fform_005foptions_0026_005fitems_005fnobody.reuse(_jspx_th_form_005foptions_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_form_005finput_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_form_005finput_005f5 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fid_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    _jspx_th_form_005finput_005f5.setPageContext(_jspx_page_context);
    _jspx_th_form_005finput_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
    // /Settings.jsp(252,14) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f5.setPath("cabDriverName");
    // /Settings.jsp(252,14) null
    _jspx_th_form_005finput_005f5.setDynamicAttribute(null, "placeholder", "Driver Name");
    // /Settings.jsp(252,14) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f5.setId("dname");
    // /Settings.jsp(252,14) null
    _jspx_th_form_005finput_005f5.setDynamicAttribute(null, "class", "form-control input");
    int[] _jspx_push_body_count_form_005finput_005f5 = new int[] { 0 };
    try {
      int _jspx_eval_form_005finput_005f5 = _jspx_th_form_005finput_005f5.doStartTag();
      if (_jspx_th_form_005finput_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005finput_005f5[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005finput_005f5.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005finput_005f5.doFinally();
      _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fid_005fclass_005fnobody.reuse(_jspx_th_form_005finput_005f5);
    }
    return false;
  }

  private boolean _jspx_meth_form_005finput_005f6(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_form_005finput_005f6 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fid_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    _jspx_th_form_005finput_005f6.setPageContext(_jspx_page_context);
    _jspx_th_form_005finput_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
    // /Settings.jsp(264,14) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f6.setPath("cabDriverPhone");
    // /Settings.jsp(264,14) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f6.setId("dph");
    // /Settings.jsp(264,14) null
    _jspx_th_form_005finput_005f6.setDynamicAttribute(null, "placeholder", "Driver Contact Number ");
    // /Settings.jsp(264,14) null
    _jspx_th_form_005finput_005f6.setDynamicAttribute(null, "class", "form-control input");
    int[] _jspx_push_body_count_form_005finput_005f6 = new int[] { 0 };
    try {
      int _jspx_eval_form_005finput_005f6 = _jspx_th_form_005finput_005f6.doStartTag();
      if (_jspx_th_form_005finput_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005finput_005f6[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005finput_005f6.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005finput_005f6.doFinally();
      _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fid_005fclass_005fnobody.reuse(_jspx_th_form_005finput_005f6);
    }
    return false;
  }

  private boolean _jspx_meth_form_005finput_005f7(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_form_005finput_005f7 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fid_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    _jspx_th_form_005finput_005f7.setPageContext(_jspx_page_context);
    _jspx_th_form_005finput_005f7.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
    // /Settings.jsp(276,14) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f7.setPath("cabCapacitystr");
    // /Settings.jsp(276,14) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f7.setId("cap");
    // /Settings.jsp(276,14) null
    _jspx_th_form_005finput_005f7.setDynamicAttribute(null, "placeholder", "Cab Capacity ");
    // /Settings.jsp(276,14) null
    _jspx_th_form_005finput_005f7.setDynamicAttribute(null, "class", "form-control input");
    int[] _jspx_push_body_count_form_005finput_005f7 = new int[] { 0 };
    try {
      int _jspx_eval_form_005finput_005f7 = _jspx_th_form_005finput_005f7.doStartTag();
      if (_jspx_th_form_005finput_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005finput_005f7[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005finput_005f7.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005finput_005f7.doFinally();
      _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fid_005fclass_005fnobody.reuse(_jspx_th_form_005finput_005f7);
    }
    return false;
  }

  private boolean _jspx_meth_form_005finput_005f8(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_form_005finput_005f8 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fid_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    _jspx_th_form_005finput_005f8.setPageContext(_jspx_page_context);
    _jspx_th_form_005finput_005f8.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
    // /Settings.jsp(288,14) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f8.setPath("cabPoc");
    // /Settings.jsp(288,14) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f8.setId("poc");
    // /Settings.jsp(288,14) null
    _jspx_th_form_005finput_005f8.setDynamicAttribute(null, "placeholder", "Cab Poc");
    // /Settings.jsp(288,14) null
    _jspx_th_form_005finput_005f8.setDynamicAttribute(null, "class", "form-control input");
    int[] _jspx_push_body_count_form_005finput_005f8 = new int[] { 0 };
    try {
      int _jspx_eval_form_005finput_005f8 = _jspx_th_form_005finput_005f8.doStartTag();
      if (_jspx_th_form_005finput_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005finput_005f8[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005finput_005f8.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005finput_005f8.doFinally();
      _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fid_005fclass_005fnobody.reuse(_jspx_th_form_005finput_005f8);
    }
    return false;
  }
}
