/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.39
 * Generated at: 2015-02-26 11:31:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class UserSignUp_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005fform_0026_005fonsubmit_005fcommandName_005fclass_005faction;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fmaxlength_005fid_005fclass_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fid_005fclass_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fform_005fform_0026_005fonsubmit_005fcommandName_005fclass_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fmaxlength_005fid_005fclass_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fid_005fclass_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fform_005fform_0026_005fonsubmit_005fcommandName_005fclass_005faction.release();
    _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fmaxlength_005fid_005fclass_005fnobody.release();
    _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fid_005fclass_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t\t<meta charset=\"utf-8\">\r\n");
      out.write("\t\t<title>Cab Application</title>\r\n");
      out.write("\t\t<meta name=\"generator\" content=\"Bootply\" />\r\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1\">\r\n");
      out.write("\t\t<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\t<link href=\"css/styles.css\" rel=\"stylesheet\">\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("<nav class=\"navbar navbar-inverse navbar-fixed-top\" role=\"navigation\">\r\n");
      out.write("      <div class=\"container-fluid\">\r\n");
      out.write("        <div class=\"navbar-header\">\r\n");
      out.write("            <p class=\"navbar-text\">Enterprise Project Cab</p>\r\n");
      out.write("        </div>\r\n");
      out.write("       <!--  <div class=\"navbar-collapse collapse\">\r\n");
      out.write("          <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("             <li><a href=\"Home.jsp\">Dashboard</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"booking.htm\">Booking</a></li>\r\n");
      out.write("            <li><a href=\"setting.htm\">Settings</a></li>\r\n");
      out.write("            <li><a href=\"#\">Help</a></li>\r\n");
      out.write("            <li><a href=\"logout\">Logout</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("         </div> -->\r\n");
      out.write("      </div>\r\n");
      out.write("</nav>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function validateform()\r\n");
      out.write("{\r\n");
      out.write("\tvar uid=document.getElementById(\"uid\").value;\r\n");
      out.write("\tvar uname=document.getElementById(\"uname\").value.toUpperCase();\r\n");
      out.write("\tvar uphone=document.getElementById(\"uphone\").value;\r\n");
      out.write("\tvar uemail=document.getElementById(\"uemail\").value;\r\n");
      out.write("\tvar count=0;\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t/* user id validation */\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t if(uid.length<6||isNaN(uid))\r\n");
      out.write("\t\t{\t\t \r\n");
      out.write("\t\t  document.getElementById(\"uidloc\").innerHTML=\"<b>Id should be 6 digit in length</b> \"; \r\n");
      out.write("\t\t  count++;\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t \telse{\r\n");
      out.write("\t\t\tdocument.getElementById(\"uidloc\").innerHTML=\"\"; \t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t/* username validation */\r\n");
      out.write("\t\r\n");
      out.write("\t if((jQuery.trim( uname )).length==0){\r\n");
      out.write("\t\t document.getElementById(\"unameloc\").innerHTML=\"<b>Name cannot contain whitespaces or blank</b>\"; \t\t\r\n");
      out.write("\t\tcount++;\r\n");
      out.write("\t }\r\n");
      out.write("\t\telse if(uname.length>1&&uname==\"ADMIN\"){\r\n");
      out.write("\t\t  document.getElementById(\"unameloc\").innerHTML=\"<b>Name cannot be ADMIN</b>\"; \t\t\t\r\n");
      out.write("\t\t\t\tcount++;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse if(uname.length>25)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t  document.getElementById(\"unameloc\").innerHTML=\"<b>User name too large</b>\";\t\r\n");
      out.write("\t\t  count++;\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tdocument.getElementById(\"unameloc\").innerHTML=\"\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t/* contact number validation */\r\n");
      out.write("\t \r\n");
      out.write("\tif(uphone.length!=10||isNaN(uphone)){\t\t \r\n");
      out.write("\t\t  document.getElementById(\"uphoneloc\").innerHTML=\"<b>Contact number should be 10 digits in length</b>\"; \r\n");
      out.write("\t\t\t\tcount++;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tdocument.getElementById(\"uphoneloc\").innerHTML=\"\"; \t\t\t \r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t/* email id validation */\r\n");
      out.write("\t \r\n");
      out.write("\t if(!(/^\\w+([\\.-]?\\w+)*@\\w+([\\.-]?\\w+)*(\\.\\w{2,3})+$/.test(uemail))||uemail==\"\"){\t\t   \r\n");
      out.write("\t\t   document.getElementById(\"uemailloc\").innerHTML=\"<b>Enter a valid email id</b>\"; \t\r\n");
      out.write("\t\t\tcount++;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse{\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"uemailloc\").innerHTML=\"\"; \t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t/* return value */\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t if(count!=0)\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t else\r\n");
      out.write("\t\t\t return true;\r\n");
      out.write("};\r\n");
      out.write("</script>\r\n");
      //  form:form
      org.springframework.web.servlet.tags.form.FormTag _jspx_th_form_005fform_005f0 = (org.springframework.web.servlet.tags.form.FormTag) _005fjspx_005ftagPool_005fform_005fform_0026_005fonsubmit_005fcommandName_005fclass_005faction.get(org.springframework.web.servlet.tags.form.FormTag.class);
      _jspx_th_form_005fform_005f0.setPageContext(_jspx_page_context);
      _jspx_th_form_005fform_005f0.setParent(null);
      // /UserSignUp.jsp(99,0) null
      _jspx_th_form_005fform_005f0.setDynamicAttribute(null, "class", "form-dashboard");
      // /UserSignUp.jsp(99,0) name = action type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fform_005f0.setAction("adduser");
      // /UserSignUp.jsp(99,0) name = commandName type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fform_005f0.setCommandName("userdto");
      // /UserSignUp.jsp(99,0) name = onsubmit type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fform_005f0.setOnsubmit("return validateform()");
      int[] _jspx_push_body_count_form_005fform_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_form_005fform_005f0 = _jspx_th_form_005fform_005f0.doStartTag();
        if (_jspx_eval_form_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("<br/>\r\n");
            out.write("    <div class=\"col-sm-8 col-md-12 main\">\t   \r\n");
            out.write("\t   <div id=\"page-wrapper\">\r\n");
            out.write("\t\t<div id=\"page-inner\">\r\n");
            out.write("                                        \r\n");
            out.write("            <div class=\"row\">\r\n");
            out.write("               <div class=\"col-md-13 col-sm-13\">\r\n");
            out.write("                    <div class=\"panel panel-primary\"  style=\"height:400px;width:900px;margin-left:210px\">\r\n");
            out.write("                        <div class=\"panel-heading\">\r\n");
            out.write("                            <center>User Signup</center>\r\n");
            out.write("                        </div>\r\n");
            out.write("\t\t\t\t\t\t<br>\r\n");
            out.write("\t\t\t\t\t\t<center>\r\n");
            out.write("\t\t\t\t\t\t ");
 
								String str1="";
								if(session.getAttribute("message")!=null){
									str1=(String)session.getAttribute("message"); 
								
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t<font color=\"red\" size=\"5\"><span>");
            out.print(str1);
            out.write("</span></font>\r\n");
            out.write("\t\t\t\t\t\t\t\t");
} 
								session.removeAttribute("message");
								
            out.write(" \r\n");
            out.write("\t\t\t\t\t\t<br/>\t\t\r\n");
            out.write("\t\t\t\t\t\t<table>\r\n");
            out.write("\t\t\t\t\t\t\t<tbody>\r\n");
            out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td><b>User ID <font color=\"red\">*</font></b></td>\t\t\t\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td><b>:</b></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td>&nbsp;&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<!-- <div id=\"uidloc\"></div> -->\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td>");
            if (_jspx_meth_form_005finput_005f0(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
              return;
            out.write("</td>\t\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td><span style=\"color:red\"  id=\"uidloc\"></span></td> \t\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td><b>User Name <font color=\"red\">*</font></b></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td><b>:</b></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td>&nbsp;&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<!-- <div id=\"unameloc\"></div> -->\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td>");
            if (_jspx_meth_form_005finput_005f1(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
              return;
            out.write("\t\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td><span style=\"color:red\" id=\"unameloc\"></span></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td><b>User Contact Number <font color=\"red\">*</font></b></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td><b>:</b></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td>&nbsp;&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<!-- <div id=\"uphoneloc\"></div> -->\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td>");
            if (_jspx_meth_form_005finput_005f2(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
              return;
            out.write("</td>\t\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td><span style=\"color:red\"  id=\"uphoneloc\"></span></td>\t\t\t\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td><b>User Email <font color=\"red\">*</font></b></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td><b>:</b></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td>&nbsp;&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<!-- <div id=\"uemailloc\"></div> -->\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td>");
            if (_jspx_meth_form_005finput_005f3(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
              return;
            out.write("</td>\t\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td><span style=\"color:red\"  id=\"uemailloc\"></span></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<td>&nbsp;</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t</tr>                                                                                                    \r\n");
            out.write("\t\t\t\t\t\t\t   </tbody>\t\r\n");
            out.write("\t\t\t\t   </table>\r\n");
            out.write("\t\t\t\t   \r\n");
            out.write("\t\t\t<br/><br/>\r\n");
            out.write("\t\t\t<input type=\"submit\" value=\"Signup\" class=\"btn btn-primary\">\r\n");
            out.write("\t\t\t<input type=\"reset\" value=\"Reset\" class=\"btn btn-primary\" onclick=\"window.location.reload()\">\r\n");
            out.write("            <br/>            \r\n");
            out.write("            </center>      \r\n");
            out.write("       </div><!-- col-->\r\n");
            out.write("                   \r\n");
            out.write("          \r\n");
            out.write("    </div><!-- row-->\r\n");
            out.write("\t\t  \r\n");
            out.write("\t\t  \r\n");
            out.write("\t\t  </div> <!-- page inner-->\r\n");
            out.write("\t\t  \r\n");
            out.write("          </div><!-- page wraper-->\r\n");
            out.write("\r\n");
            out.write("     \r\n");
            out.write("\t</div><!-- main-->\r\n");
            out.write("\r\n");
            int evalDoAfterBody = _jspx_th_form_005fform_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_form_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_form_005fform_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_form_005fform_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_form_005fform_005f0.doFinally();
        _005fjspx_005ftagPool_005fform_005fform_0026_005fonsubmit_005fcommandName_005fclass_005faction.reuse(_jspx_th_form_005fform_005f0);
      }
      out.write("\r\n");
      out.write("<hr>\r\n");
      out.write("<footer>\r\n");
      out.write("  <p class=\"text-center\">©2014 Cognizant Technology Solutions</p>\r\n");
      out.write("</footer>\r\n");
      out.write("        \r\n");
      out.write("\t<!-- script references -->\r\n");
      out.write("\t\t<script src=\"js/jquery-1.10.2.js\"></script>\r\n");
      out.write("\t\t<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"js/scripts.js\"></script>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_form_005finput_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_form_005finput_005f0 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fmaxlength_005fid_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    _jspx_th_form_005finput_005f0.setPageContext(_jspx_page_context);
    _jspx_th_form_005finput_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
    // /UserSignUp.jsp(131,13) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f0.setPath("userId");
    // /UserSignUp.jsp(131,13) null
    _jspx_th_form_005finput_005f0.setDynamicAttribute(null, "placeholder", "Your Associate Id ");
    // /UserSignUp.jsp(131,13) null
    _jspx_th_form_005finput_005f0.setDynamicAttribute(null, "class", "form-control input");
    // /UserSignUp.jsp(131,13) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f0.setId("uid");
    // /UserSignUp.jsp(131,13) name = maxlength type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f0.setMaxlength("6");
    int[] _jspx_push_body_count_form_005finput_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_form_005finput_005f0 = _jspx_th_form_005finput_005f0.doStartTag();
      if (_jspx_th_form_005finput_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005finput_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005finput_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005finput_005f0.doFinally();
      _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fmaxlength_005fid_005fclass_005fnobody.reuse(_jspx_th_form_005finput_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_form_005finput_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_form_005finput_005f1 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fid_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    _jspx_th_form_005finput_005f1.setPageContext(_jspx_page_context);
    _jspx_th_form_005finput_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
    // /UserSignUp.jsp(145,13) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f1.setPath("userName");
    // /UserSignUp.jsp(145,13) null
    _jspx_th_form_005finput_005f1.setDynamicAttribute(null, "placeholder", "Your Name");
    // /UserSignUp.jsp(145,13) null
    _jspx_th_form_005finput_005f1.setDynamicAttribute(null, "class", "form-control input");
    // /UserSignUp.jsp(145,13) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f1.setId("uname");
    int[] _jspx_push_body_count_form_005finput_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_form_005finput_005f1 = _jspx_th_form_005finput_005f1.doStartTag();
      if (_jspx_th_form_005finput_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005finput_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005finput_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005finput_005f1.doFinally();
      _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fid_005fclass_005fnobody.reuse(_jspx_th_form_005finput_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_form_005finput_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_form_005finput_005f2 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fmaxlength_005fid_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    _jspx_th_form_005finput_005f2.setPageContext(_jspx_page_context);
    _jspx_th_form_005finput_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
    // /UserSignUp.jsp(159,13) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f2.setPath("userPhone");
    // /UserSignUp.jsp(159,13) null
    _jspx_th_form_005finput_005f2.setDynamicAttribute(null, "placeholder", "Your Contact Number ");
    // /UserSignUp.jsp(159,13) null
    _jspx_th_form_005finput_005f2.setDynamicAttribute(null, "class", "form-control input");
    // /UserSignUp.jsp(159,13) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f2.setId("uphone");
    // /UserSignUp.jsp(159,13) name = maxlength type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f2.setMaxlength("10");
    int[] _jspx_push_body_count_form_005finput_005f2 = new int[] { 0 };
    try {
      int _jspx_eval_form_005finput_005f2 = _jspx_th_form_005finput_005f2.doStartTag();
      if (_jspx_th_form_005finput_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005finput_005f2[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005finput_005f2.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005finput_005f2.doFinally();
      _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fmaxlength_005fid_005fclass_005fnobody.reuse(_jspx_th_form_005finput_005f2);
    }
    return false;
  }

  private boolean _jspx_meth_form_005finput_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_form_005finput_005f3 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fmaxlength_005fid_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    _jspx_th_form_005finput_005f3.setPageContext(_jspx_page_context);
    _jspx_th_form_005finput_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
    // /UserSignUp.jsp(173,13) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f3.setPath("userEmail");
    // /UserSignUp.jsp(173,13) null
    _jspx_th_form_005finput_005f3.setDynamicAttribute(null, "placeholder", "Your Email ");
    // /UserSignUp.jsp(173,13) null
    _jspx_th_form_005finput_005f3.setDynamicAttribute(null, "class", "form-control input");
    // /UserSignUp.jsp(173,13) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f3.setId("uemail");
    // /UserSignUp.jsp(173,13) name = maxlength type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_form_005finput_005f3.setMaxlength("30");
    int[] _jspx_push_body_count_form_005finput_005f3 = new int[] { 0 };
    try {
      int _jspx_eval_form_005finput_005f3 = _jspx_th_form_005finput_005f3.doStartTag();
      if (_jspx_th_form_005finput_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_form_005finput_005f3[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_form_005finput_005f3.doCatch(_jspx_exception);
    } finally {
      _jspx_th_form_005finput_005f3.doFinally();
      _005fjspx_005ftagPool_005fform_005finput_0026_005fplaceholder_005fpath_005fmaxlength_005fid_005fclass_005fnobody.reuse(_jspx_th_form_005finput_005f3);
    }
    return false;
  }
}
